### ISSUE TITLE
Icon problem

### ISSUE THREAD

**Issue by Maximusvin** [desertptu4ka/goit-team-project-js#21]
Icon not showing:
https://github.com/desertptu4ka/goit-team-project-js/blob/7a9a9a5a971f20eed095feb1ba7a6aeb9f65ee0f/src/js/header.js#L60-L62

**Comment by desertptu4ka** [comment]
we are familiar with this problem.
the fact is that to add pictures/sprites dynamically, we need to use the following command:

```
import * as anyNameThatYouWant from '../images/bg-home-320-1x-min.jpg';

div.innerHTML = `<img src="${anyNameThatYouWant }" alt="abc" />`;
```

we are still working on it.

**Comment by Maximusvin** [comment]
OK

To dynamically render icons in a sprite, you can use the following approach:
```
import icon from '../images/sprite.svg';

const addIcon = () => `<svg class="header__icon">
        <use href="${icon}#icon-main-logo"></use>
      </svg>`;
```
