### ISSUE TITLE
Unnecessary link

### ISSUE THREAD

**Issue by Maximusvin** [desertptu4ka/goit-team-project-js#22]
Link is not needed here. This is not a transition to another page. By clicking on the movie card, a modal should open.

https://github.com/desertptu4ka/goit-team-project-js/blob/7a9a9a5a971f20eed095feb1ba7a6aeb9f65ee0f/src/js/card-templete.js#L10-L15

**Comment by desertptu4ka** [comment]
thanks.
I assume we will remove <a> tag and just add `style cursor: pointer;`
